print("Hello, GitHub!")
print("My name is Anusha S.")
print("Department: ECE")
print("This is my first repository.")
print("I am learning Git and GitHub.")
print("Version control is useful.")
print("GitHub helps in collaboration.")
print("This program is for academic activity.")
print("Thank you for visiting my repository.")
print("Have a great day!")print("Hello, GitHub!")